FROM node:slim as build
RUN npm install yarn --global
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN yarn install
COPY . .
RUN yarn build

FROM nginx:1-alpine3.18-slim
COPY --from=build build usr/share/nginx/html
EXPOSE 80