FROM node:slim as build
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install
ARG REACT_APP_LOCALHOST_KEY
ARG REACT_APP_BACKEND_URL
ENV REACT_APP_LOCALHOST_KEY=$REACT_APP_LOCALHOST_KEY
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL
COPY . .
RUN npm run build

FROM nginx:1-alpine3.18-slim
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80