apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: suraj49470/3-tier-backend:1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URL
              value: mongodb://admin:admin@mongodb-svc:27017/chats?authSource=admin
          ports:
            - containerPort: 5000
          readinessProbe :
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 120
            periodSeconds: 5
            livenessProbe:
              httpGet:
                path: /health
                port: http
                scheme: HTTP
              initialDelaySeconds: 120
              timeoutSeconds: 5
