apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: suraj49470/3-tier-backend:1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URL
              value: mongodb://mongodb-svc?directConnection=true
          ports:
            - containerPort: 5000

